spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/houpu_goods?serverTimezone=UTC
    username: root
    password: 123456


  mvc:
      throw-exception-if-no-handler-found: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
